# Generated by Django 3.1.7 on 2021-07-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourn',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='john.tourn'),
        ),
    ]
