# Generated by Django 3.1.7 on 2021-07-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0004_results_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='result',
        ),
        migrations.AlterField(
            model_name='results',
            name='when',
            field=models.DateField(null=True),
        ),
    ]
