# Generated by Django 3.1.7 on 2021-07-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0006_results_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='title',
        ),
        migrations.AddField(
            model_name='results',
            name='result',
            field=models.CharField(default='WIN 5-0', max_length=100),
        ),
    ]
