# Generated by Django 3.1.7 on 2021-07-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0011_portfolio_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='Video Title', max_length=50),
        ),
    ]
