# Generated by Django 3.1.7 on 2021-07-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0012_auto_20210721_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=50),
        ),
    ]
