# Generated by Django 3.1.7 on 2021-07-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0013_auto_20210721_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='greetings_2',
        ),
    ]
