# Generated by Django 3.1.7 on 2021-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0014_remove_home_greetings_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
