# Generated by Django 3.2 on 2021-07-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0017_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
